### ISSUE TITLE
modified Streetcomplete in F-Droid

### ISSUE THREAD

**Issue by tiptoptom** [Helium314/SCEE#365]
Would it be conceivable that the modified Streetcomplete will become available in F-Droid?

**Comment by Helium314** [comment]
I don't plan on doing this. This is still mainly a "playground" and not the _experienced mapper edition_ envisioned in https://github.com/streetcomplete/StreetComplete/discussions/3003.
Plus, modifications are badly documented, and this modified version is not as safe as vanilla SC (users may enter bad OSM data more easily). Basically I don't want to bring too much attention to this version... that's something for the _experienced mapper edition_, if it ever will be realized.

**Comment by tiptoptom** [comment]
Ok. I didn't know this discussion before.

If I understand correctly, the experienced mapper edition failed due to low demand? But little attention to this version contradicts that. Wouldn't the solution be to require a certain number of stars?

**Comment by Helium314** [comment]
It's more like there was no outcome in the discussion about what should actually be in this edition, and who would maintain it (I don't want to do it alone, as my available time fluctuates a lot).

Currently I simply add / change whatever idea seems good to me, if I can add it with a low amount of work.

**Comment by Helium314** [comment]
Hmm, from the number of reactions here I'm a bit surprised there are more people reading here than I expected... so some more thoughts on this topic:

A start would be that I don't want to do it alone, as then there will always be the "personal playground" feeling for me.
Maybe we could discuss about joining forks with @mnalis... this might end up being more efficient than the current state of two similar but separate versions.
Though in the beginning it's probably quite some work to (re-)implement all/most the changes in optional ways (hardcoding is much easier). The result would ideally be something close to vanilla SC by default, but with a lot of customization options. And more organized/documented changes that what I did so far.

The once there actually is a reasonably well working app, we can discuss about publishing on F-Droid, and about ways to clearly warn/remind users that they can do more damage with this than with vanilla SC.

**Comment by Helium314** [comment]
> there are also some things in h3 that I don't like

I am aware of that, and that's why I explicitly wanted to have everything optional... or almost everything... depends on the amount of work.
E.g. I have split the building type quest into two quests, one asked for buildings with address (low priority) and one for buildings without address (higher priority), I don't see how to make this optional in a _simple_ way.

> having the way to export/import all the preferences would help a lot there too as there would be even bigger number of them, but that is just a wishlist

Acctually exporting shared preferences should be easy (just copy the xml), only difficulty is the quest profiles which are in the database.

**Comment by Helium314** [comment]
@mnalis I just uploaded a new branch with most of the modifications and made most of them optional. You can add your changes as well.

There are still some things that could be improved:
* use different email for bug reports
* need to restart the app to apply some settings changes (3D buildings, quick settings button, quest settings)
* some quests don't have their own icon (website, remove wrong surface, service building, cuisine, outdoor seating type)
* added building types always re-use other icons
* new crossing types re-use existing images
* no way of providing / getting files (for GPX notes and external quest)

And some changes that are not optional, not sure if you're ok with it:
* hide button
* prefer GPS over network location (unless much less accurate)
* use last known location at start (up to 2 min old)
* reduce auto-completion threshold
* show surface tag in smoothness quest
* additional answers (private, demolished, show/edit tags)
* pause upload when downloading
* move "no cycleway" answer
* raised crossing and zebra crossing answers

**Comment by NotSoImportant** [comment]
So you have specific guidance / ideas how someone can help with testing? Or are you talking about test code?

**Comment by Helium314** [comment]
Finding potentially bad behavior is always something useful, e.g. I was not aware of the badly located hide button (#367).

But for the idea of publishing on F-Droid... currently not.
The roughly sketched idea of a plan is:
* arrange some things with @mnalis that should be fixed from the start (which repo to use, app name, mail for bug reports, banned version checker,...)
* add further functionality from @mnalis fork
* the things mentioned above
* create a bunch of issues for new feature ideas
* once everything works well enough we can think about F-Droid

**Comment by mnalis** [comment]
> And some changes that are not optional, not sure if you're ok with it:
> 
>     * hide button

While I personally like it, I think it should be optional, as it changes UI quite visibly (and can lead to problems like https://github.com/Helium314/StreetComplete/issues/371).

>     * prefer GPS over network location (unless much less accurate)

Is that only when both are enabled? Maybe should make it optional, as GPS draws quite a bit of power?
But I'm not sure what upstream does (and why)...

>     * use last known location at start (up to 2 min old)

Uh, I wasn't even aware it isn't default behaviour upstream, it does seem to return me to location that was last displayed?

>     * reduce auto-completion threshold

I think it can stay reduced always.

>     * show surface tag in smoothness quest

Extra information like that can stay unconditionally.

>     * additional answers (private, demolished, show/edit tags)

Extra options (tucked away in menu entries) can too stay unconditionally.
 
>     * pause upload when downloading

That sounds always reasonable to me (provided it is not buggy, e.g. upload fails because of it or something), so if extra preference is too much work, we can live without it. 

>     * move "no cycleway" answer

Ah. I love new position better (as it is quite common answer, so ergonomically it is better), but people used to upstream might have muscle memory trained to original behaviour... but can probably stay unconditional unless someone has a reason for it not to.

>     * raised crossing and zebra crossing answers

Extra answers are generally ok, however it would be good to have different pictures. It is quite confusing currently.

**Comment by stephan75** [comment]
Is it true that https://apt.izzysoft.de/fdroid/index/apk/de.westnordost.streetcomplete.expert is available since august 2022 via izzy repo?

**Comment by mnalis** [comment]
@stephan75 Are you concerned about exact date, or whether the `.apk` you download from there is the same app whose source you see here? If the latter, the most precise answer is ***"probably"*** (i.e. izzysoft was as far as I recall expressing interest to publish it).  :smile: 

---

But in its core, that is a matter of **trust**, which we cannot answer for you. The link you posted ***claims*** the source was obtained from here (i.e. https://github.com/Helium314/StreetComplete). However, for `.apk` downloaded from the link you posted to **_actually_** correspond to source you see here, you'd have to trust at least:

- Microsoft (that its GitHub provided correct and not maliciously modified source to izzysoft)
- IzzySoft (that they themselves did not maliciously modify that source)
- Google, JetBrain and others for compile toolkit (that it did not maliciously miscompile the source)
- webhoster used by IzzySoft that they did not subvert signing/publishing process of compiled `.apk`s
- internet backbone providers (and security of their equipment and influence of government agencies etc.), that the allegedly secure TLS transactions happening for data exchanges above were not meddled with
- random authors and random hosters/pipelines of software libraries included in StreetComplete EE
- possibly many other parties in the pipeline...

While that might sound frightening, it is computing security reality of today's world.

On the bright side, it's likely much safer than downloading some random app on Google Play :wink:

**Comment by Helium314** [comment]
Yes, it's been available for a while on Izzy's repo. Though I didn't check whether the file available there is the same I uploaded to GitHub.

As for the origianl issue, I'm thinking about publishing on F-Droid again, but see 3 main issues
* the arcore issue (which should be solved soon I hope)
* likely much more activity / issues on GitHub, and currently I don't want to spend much time on this
* I noticed a considerable fraction of EE users are new OSM users, often without any edits with other editors. It might just be multi-accounts, but often enough notes suggest otherwise. I'm afraid new users without further OSM experience might unknownignly do bad edits using EE-specific capabilities. Things like the warning/info on first start are likely quickly forgotten or not even read, so I'm not sure what could (or even should) be done here.

**Comment by tiptoptom** [comment]
>     * I noticed a considerable fraction of EE users are new OSM users, often without any edits with other editors. It might just be multi-accounts, but often enough notes suggest otherwise. I'm afraid new users without further OSM experience might unknownignly do bad edits using EE-specific capabilities. Things like the warning/info on first start are likely quickly forgotten or not even read, so I'm not sure what could (or even should) be done here.

Would it be an option to lock the EE-version for users who have less than x edits in OSM?

**Comment by mnalis** [comment]
> I'm afraid new users without further OSM experience might unknownignly do bad edits using EE-specific capabilities. Things like the warning/info on first start are likely quickly forgotten or not even read, so I'm not sure what could (or even should) be done here.

I agree, I'm afraid publishing in F-droid (or google play) would do **more harm than good**:
- firstly, what is being said already - I think the fact that SC EE is hidden from "average Joe" (by not being published in default repos like F-droid of Gplay) is a good thing. It acts as an easy filter to weed out majority of newbies who might just click "next" without understanding the issue.
- there is additionally the issue of confusion - if there are **two** similarly named apps in the the **same** repository, where one has _"Expert Edition"_ (or _"Gold"_ or _"Pro"_ etc.) and another one _doesn't_, most users will click on the "better" one, regardless if they **need** it -- and I at least think we should actively promote SC EE only to users that would _actually benefit_ from its extensions. Majority of the users would actually find original vanilla StreetComplete as a simpler and thus better match for them.  
- One might actually find such behaviour as unsportmanship-looking, i.e. trying to promote own fork by taking majority of the work done by original author, extending it a little, and then trying to push them out by competing in the _same_ arena. So unless original author goes MIA or hostile, I personally would be more comfortable to keep situation as it is (i.e. **not** push for EE fork in F-droid/Google play).
- also, the more advanced users who  care about autoupdate should have no problems with adding extra IzzySoft repository in their f-droid setup anyway, so there is not much benefit of having F-droid version in the first place.
- One extra place to watch (and fix if it breaks) is one more task to do. So, unless it brings clear benefits (and to me it does not seem that it does), probably no one really wants extra work :smile: 
 
> Would it be an option to lock the EE-version for users who have less than x edits in OSM?

Well, it does not particularly good proxy for OSM expertise (e.g. user who added thousands of _"how many floors does this building have?"_ is not necessarily any more knowledgeable about OSM tags and mapping practices than some who did only dozen edits in JOSM. In fact, it might even likely be reverse). 

And it would hurt special events  (e.g. someone organizes mapping party, where the organizes prepare custom overlay or external quest list for otherwise newbies)

**Comment by Helium314** [comment]
Actually I think people with OSM experience might often not know about Izzy's repo or even F-Droid (though I'm definitely not going to touch Google store anyway).
The current "filter" thus imo is currently not the right one.

I don't think that two similar apps would really be an issue, e.g. there is also Syncthing and Syncthing fork, which is an extended version of Syncthing and definitely has much less activity visible on GitHub.
Then I remember the claim that something around 90% of SC users are installing from Google Store, so there is no real "competition" about a significant number of users.
Still I think an F-Droid description should clearly and quickly scare off "normal" SC users. Things like mentioning missing translations, experimental and possibly broken features, or "if you're new, try normal SC first"... and maybe the missing gamification is could help too.

I agree that locking by number of edits/changesets is not a good thing, especially because it's rather easy to get a large number of changesets just using SC for a few days.
EE could require having edits made in other editors, but simple finding those is too much work for me.

**Comment by tiptoptom** [comment]
I think, the issue can be closed? 🙈😁

**Comment by Helium314** [comment]
It can remain open for now... actually I would like to publish on F-Droid, but still not confident enough.
Maybe hide some more possibly dangerous options/other answers (e.g. edit tags) in the settings, so users definitely need to opt in and click past another warning message.
User who never check the settings will just have a slightly changed version of StreetComplete without statistics and with some missing translations.

@westnordost would you see EE on F-Droid as acceptable at all? Especially given the points in https://github.com/Helium314/StreetComplete/issues/365#issuecomment-1369144337
If not, then we can close this.

**Comment by westnordost** [comment]
I've read mnalis comment you linked and I mostly agree with it.

Although I do share these concerns, it's your choice in the end. If you do it, then IMO you should make very clear,  best even in the title, what to expect. After all,  who wouldn't like to have the version of an app that is the original  plus more? I am not sure if it can become clear enough what using the "plus more" implies.

All of us here know that there are good reasons why SC imposes certain limitations, if users want to exceed these,  they must know what they are doing. Reminiscent for what users came to expect of the app Streetcomplete is for example that guy who "with complete trust in the technology" measured very wrong distances with the AR measurement  without noticing it or the many iterations on clearer display and warnings when the user is about to remove that a road is not a oneway for cyclists (https://community.openstreetmap.org/t/when-does-streetcomplete-remove-oneway-bicycle-no/7586/6?u=westnordost).

If installing the expert edition is so convenient that it is just one tap away, I fear there will be many users who actually ought to not use SCEE but still do and this may result in many cases where (such) users are not circumspect enough when editing with the additional capabilities. And/or users and osm contributors come here and open issues about that the app should not allow this or that or show big warnings or should in this or that case automatically.... you know, etc.

It's fine that it is on izzy's repo.

**Comment by Helium314** [comment]
I still decided to try it; in absolutely worst case I'll need to remove it again.

I updated metadata with a new [description](https://github.com/Helium314/StreetComplete/blob/modified/metadata/en/full_description.txt) that explicitly states EE aims for experienced users, and discourages new users from starting with EE.
Almost all added editing capabilities are now disabled or hidden unless enabled in settings (which shows another warning). If a new user decides to ignore the app description, the EE message on first start, _and_ the warning when enabling expert mode, then I cannot help them if they use EE capabilities to make bad edits.

**Comment by Helium314** [comment]
... so I guess I'll rename the app to... StuffComplete, or StrootComploot, or whatever. Any ideas about this, or about what can be done when people don't even know which app they are using?
I don't want anyone to open EE issues in SC repo.

**Comment by Misalf-git** [comment]
StreetConcrete

**Comment by westnordost** [comment]
HeliumComplete

ExpertComplete

scee

**Comment by SLMapper** [comment]
StreetIndeed

StreetRetread

StreetRevise(d)

**Comment by mnalis** [comment]
> ExpertComplete

Sounds nice to me. Descriptive, keeps in line with "SC ExpertEdition", yet name very different from StreetComplete so no confusion hopefully - but still traces lineage to StreetComplete.

**Comment by tiptoptom** [comment]
Or StreetExpert?

**Comment by Helium314** [comment]
Thanks a lot for all the suggestions!

I decided to go with a boring one that requires only relatively few changes: SCEE
This is sort of backwards compatible, but still a name that's clearly different from StreetComplete (especially there is no chance that there is confusion from the launcher name)

**Comment by matkoniecz** [comment]
>  E.g. I have split the building type quest into two quests, one asked for buildings with address (low priority) and one for buildings without address (higher priority), I don't see how to make this optional in a simple way.

That seems handled by ability to disable/enable quests and reorder quests? You end maybe not with 1:1 exact situation as in basic SC but you can achieve the same effect. And 1:1 situation is impossible anyway as you have some extra settings.

**Comment by Helium314** [comment]
Yes, just disable/enable and reorder quests is enough if exact 1:1 is not required.

But anyway I removed that split after the address overlay was implemented, as this is much more efficient for adding addresses, and the split quest had some (minor) issues, plus maintainance effort.

**Comment by matkoniecz** [comment]
I want to suggest removal of star counter (maybe replacing it with "this is SCEE"?)

There was already one user reporting SCEE stars not increasing as StreetComplete bug, in case of wider release this type of confusion would be likely repeating

**Comment by Helium314** [comment]
Makes sense. Probably I'll keep the star (because of the progressView), with the counter invisible.

**Comment by HolgerJeromin** [comment]
JFYI: The star is missing a shadow at my device.

**Comment by mnalis** [comment]
ref: https://f-droid.org/en/packages/de.westnordost.streetcomplete.expert/

**Comment by tiptoptom** [comment]
how complex is it to bring beta releases to f-droid? :see_no_evil:

**Comment by mnalis** [comment]
> how complex is it to bring beta releases to f-droid?

Hmmm, taking a look, it seems f-droid build server **is** attempting to build SCEE 53.2 (5303), but is failing: https://monitor.f-droid.org/builds/log/de.westnordost.streetcomplete.expert/5303#site-footer

**Comment by Helium314** [comment]
The first time it failed because I forgot to remove some auto-backup file from merging SC changes.
Now there seems to be only a difference in auto-generated resources.arsc, but not any other file.

I'll try building once again later...

**Comment by Helium314** [comment]
I built 53.2 again, for whatever reason the new APK is different to my previous one.
Uploaded the new APK, so maybe it works now...

**Comment by mnalis** [comment]
>  Uploaded the new APK, so maybe it works now...

Yup, SCEE 53.2 seems to be have landed in F-droid now @tiptoptom 
(it is marked as regular release though; we would new some special tagging and recipe update if we wanted F-droid to distinguish them)
