### ISSUE TITLE
Nearby notification does not play sound

### ISSUE THREAD

**Issue by NotSoImportant** [Helium314/SCEE#400]
Backlinking to https://github.com/streetcomplete/StreetComplete/issues/48#issuecomment-1280043252

The sc ee feature "notify about nearby quests" correctly shows notifications after disabling batery saving for sc ee.
There is a permanent notification as "watchdog" + another one when quests are nearby. 

Problems I faced:
- first some-hundred meters / minutes the nearby notification did not show up at all (although I walked next to quests) 
- notification did not play any sound or vibration ever
- radius is imho set too big. While walking around it notified about ~50m far quests as "nearby". Resulting in the notification beeing often permanently present (with my chosen preset).

**Comment by Helium314** [comment]
The whole "nearby quests" thing is rather experimental right now, and might stay for a while because I don't use it...

> * first some-hundred meters / minutes the nearby notification did not show up at all (although I walked next to quests)

This is because currently there is only a passive location monitor in use, to avoid using too much battery.
So currently you will need to enable some other app that requests locations.

This isn't really great, but I'm not sure how to do the location requests...
There are several ways how this could be done... since you're interesting in using this feature, do you have some ideas?
I could just permanently enable GPS, but that would be really bad for battery while SC is running. Or SC could only use network-based location, which will be less precise and will not work always / for everyone. Or SC could enable GPS for a few seconds in regular intervals, like every 2 minutes, which will use much less battery, but again lead to missed quests.

> * notification did not play any sound or vibration ever

This is strange, sound works on my phone.
Vibrate doesn't, and apparently needs to be enabled. This will be in the next version.
You can also enable vibration manually in the app settings (long press launcher icon -> app info > notifications).

> * radius is imho set too big. While walking around it notified about ~50m far quests as "nearby". Resulting in the notification beeing often permanently present (with my chosen preset).

Here I find it hard to find a reasonable setting. In a city with many quests around a smaller radius is probably preferrable, but then you don't really need the feature...
In less densely populated areas imo a higher radius is preferrable. Probably best would be adding a setting.

**Comment by Helium314** [comment]
Next version will allow setting search radius and active use of GPS.

**Comment by NotSoImportant** [comment]
Wanted to confirm this is working well now. Thanks a lot! ❤️ 
Configurable radius and active gps polling makes it useful. 
Using it not regularly, but from time to time and it works as expected, also with notifications now. 🎉
