### ISSUE TITLE
Add possibility to add/save multiple custom overlays

### ISSUE THREAD

**Issue by SLMapper** [Helium314/SCEE#404]
**Use case**
Want to use different custom overlay for different use cases and be able to switch between them

**Why**
- Defining the overlay can be quite complex, so I want to retain it (_this could theoretically be done in any separate text app_)
- Defining two custom overlays to quickly switch between them it currently not possible 

**Proposed Solution**
In the editor: 
- Add field to give it a name
- Add a delete button

In the list of overlays
- Store different custom overlays as separate entry
- Rename the "custom overlay" button to "edit"
- Make it sensitive to the selected quest
  - will edit the selected overlay
  - only enabled when a custom overlay is selected

**Comment by Helium314** [comment]
I see a few issues here
* I currently don't want to spend much time on development (sorry, though this will likely improve)
* The internal structure of SC doesn't allow for simply adding and removing overlays by the user, so there can only be something like "custom overlay 1 / 2 / 3 /..." (though it should be possible to rename them). Anyway, the point is that the number will always be limited.
* SC will change overlay selection UI at some point, and I really dislike working on UI stuff. Thus I want to avoid doing that work twice, and wait for SC to switch UI first.

Otherwise having multiple custom overlays is definitely something that could be implemented.

**Comment by Helium314** [comment]
Next version will contain a setting to import / export custom overlays (previously they were part of the normal settings export). This should improve switching at least a little bit.

For the multiple overlays, it should actually be possible to add an arbitrary number of them by re-using the same overlay internally and just changing settings. Depending on the to-be-done UI, it might be possible to make it look like having multiple overlays, maybe even with a customizable name.

**Comment by SLMapper** [comment]
Import export works 🙂 Thank you.
If you / somebody will find the time to make it more convinient like 
> For the multiple overlays, it should actually be possible to add an arbitrary number of them by re-using the same overlay internally and just changing settings. Depending on the to-be-done UI, it might be possible to make it look like having multiple overlays, maybe even with a customizable name.

it will be great

**Comment by Helium314** [comment]
It's definitely planned, but I'd like to wait for the update to the overlay selection menu, so I don't need to re-do the UI possibly in a few weeks.

**Comment by Helium314** [comment]
This is now implemented in a way that should not need (large) changes when the selection UI changes later. Could you please test it? [Link](https://github.com/Helium314/SCEE/releases/tag/v51.1_custom_overlay_test)
Everything should work, but if something goes really wrong there is a risk of losing your current custom overlay settings. So it's safer to export your overlays first.

You can add all of your exported overlays by importing them one by one, and selecting "add".

**Comment by NotSoImportant** [comment]
It generally works well (with some limitations)! Thank you 🏆 

Things I recognized:
1. _import_ &rarr; _custom overlay_
    - "add" does not work with exported overlays (in old format?) - maybe only once you already have some in the new format
    - "replace" actually replaces content of the first (default) custom overlay, even if it already contained content and even if it had a custom name. this making it look like it did not work when only looking at the list of overlays (and not its content)
2. _custom overlay_ &rarr; _manage_ deleting an entry leads to leaving the context (maybe to not have to clean up when you delete the currently opened one)
3. overlay selection gets lost in the following case:
    1. have at least 2 custom overlays
    2. have a custom overlay selected (and applied with "ok")
    3. open list of overlays, click on another custom overlay
    4. click "manage"
    5. click "ok" or "cancel"
    6. (open list of overlays again and see that "none" is selected)
4. when adding a new custom overlay via _manage_ &rarr; _add_ sometimes they are copied from existing, sometimes they are empty - have not found out when
5. when adding a new custom overlay and then pressing "cancel" in the custom overlay dialog, the new custom overlay was still created

**Comment by Helium314** [comment]
> "add" does not work with exported overlays (in old format?) - maybe only once you already have some in the new format

This definitely needs to work and should add the imported overlay last. Looks like some bug.

> "replace" actually replaces content of the first (default) custom overlay

This is intentional, and I think it's not too surprising that an overlay might be replaced. I also considered removing all existing custom overlays before when choosing replace.

>  deleting an entry leads to leaving the context (maybe to not have to clean up when you delete the currently opened one)

What did you expect to happen? It could also show the updated manage dialog (and then probably replace _cancel_ with _close_ for the button)

> overlay selection gets lost in the following case

Thanks for the steps, I'll look into it. But this might be a case of too much work for fixing a minor inconvenience.

> sometimes they are copied from existing

Could it be that you had imported this existing overlay with _add_ before? This could be related to 1.

> when adding a new custom overlay and then pressing "cancel" in the custom overlay dialog, the new custom overlay was still created

Since this is only a minor inconvenience, I'd rather only fix this if I find a simple way.

**Comment by Helium314** [comment]
1 . and possibly 4. should be fixed in https://github.com/Helium314/SCEE/commit/bb4b83e3278b0c8db5ffdfd56602daa90528e6e0
5 . and maybe 2. and 3. should be fixed in https://github.com/Helium314/SCEE/commit/39db7a75efc60c4c4a737ff494c1d975716d556b

I can't test it for the next few days, but if you want to give it another try: https://github.com/Helium314/SCEE/actions/runs/4445442463 / https://github.com/Helium314/SCEE/suites/11626796574/artifacts/603342855

**Comment by NotSoImportant** [comment]
apk seems broken

**Comment by Helium314** [comment]
What seems broken? Can't install?

**Comment by NotSoImportant** [comment]
Yes

**Comment by Helium314** [comment]
This is weird, works for me... does the installer show any useful error message indicating the reason?

Anyway, there is another one available: https://github.com/Helium314/SCEE/actions/runs/4456557207 / https://github.com/Helium314/SCEE/suites/11652583573/artifacts/605210224

**Comment by NotSoImportant** [comment]
Same again 
![Screenshot_20230318-211545](https://user-images.githubusercontent.com/35758921/226136693-6e3aedc2-fbb9-40d6-9707-7c280c470afe.png)

**Comment by NotSoImportant** [comment]
It only worked for me after reinstalling the app.

---

Now as expected
- _import_ &rarr; _replace_ will replace all overlays
- create and cancel will not create a new custom overlay
- deleting in _manage_ dialog brings up _manage_ dialog again
- "ok" selects the currently edited custom overlay

Issues
1. _import_ &rarr; _add_ will create a new custom overlay entry, but with copying the content of the first custom overlay instead of the to be imported one
2. still loosing context / imho not intuitive result after pressing ok, cancel buttons

Suggestion for 2
- put "manage" button into the list of overlays (or a settings icon button if otherwise too narrow)
- (rename "custom overlay" button to "customize")
- clicking any button in these dialogs ("cancel" or "ok" in the _custom overlay_, "close" in the _manage_ dialog) will bring up the overlay list (like returning to it)
    - By this you will be able to directly see the impact of your chosen action

**Comment by Helium314** [comment]
> It only worked for me after reinstalling the app.

This is even weirder. After uninstalling SCEE the package is not corrupt any more?
Actually it looks like mismatching keys, but with a misleading error message, Only... they match, and upgrading works on my phone.
Which Android version are you using? Probably something newer than my Android 9 I guess.

> still loosing context / imho not intuitive result after pressing ok, cancel buttons

This is something where too many changes are needed for a relatively small impact. Especially considering that these changes will need to be re-done once the SC UI for overlay selection changes (which was already announced somewhere).
I would accept a PR on this though.

**Comment by NotSoImportant** [comment]
Ok, thanks

**Comment by Helium314** [comment]
I compared the APK from GitHub workflow https://github.com/Helium314/SCEE/actions/runs/4456557207 with my home-built and couldn't find any difference in signing keys or contained data, so still no idea why it doesn't work for you...

Import should really be fixed now in https://github.com/Helium314/SCEE/commit/a7bf7acf8a7fe563327960bbd3ff9ec96e8d1043

**Comment by NotSoImportant** [comment]
_Import_ &rarr; _add_ works.

But I encountered another bug:
- when exporting multiple overlays at once and importing them again (with _replace_), the first custom overlay contains content of the previously selected overlay.

**Comment by NotSoImportant** [comment]
Previous selection is stored in the exported settings

**Comment by Helium314** [comment]
Ah, that's probably an issue with old and new overlays in one file, which was only possible in the testing versions (and files exported with them).
On version upgrade, old overlay settings are converted to new ones to prevent this. But the testing version was still not 52.0.

You can fix such exported overlay files manually by changing _custom_overlay_filter_ to _custom_overlay_<number>_filter_ and _custom_overlay_color_key_ to _custom_overlay_<number>_color_key_, and adding the number to the _custom_overlay_indices_ list.
Just make sure to choose a number that's not already used.

**Comment by NotSoImportant** [comment]
Anyhow. As it is working fine with exports from current version and there was not a huge time in between that should be fine. Thank you

**Comment by Helium314** [comment]
Thanks for the steps and your persistence.
The reason for this is that old (non-indexed) overlay settings where copied to new (indexed) settings, but never removed...

It's fixed now, and in the next version overlays exported with a buggy version will be fixed / import correctly.

**Comment by SLMapper** [comment]
🎉 nice job. I love it ❤️
