### ISSUE TITLE
Enable 'Is cash payment accepted here?'  quest in the Netherlands

### ISSUE THREAD

**Issue by meiphoo7-Mae** [Helium314/SCEE#413]
**Use case**

While it is legally required in the Netherlands to accept cash payments, according to research done by an organisation for senior/elderly citizens about 2-5% of the shops only accepts electronic payments. They focused on shops but it might be equally valid for other places where payments are accepted.

(Update: according to another newspaper article it isn't even legally required in the Netherlands for places to accept cash payments, so I now wonder why that quest is disabled in the Netherlands.

**Proposed Solution**

Enabling the 'Is cash payment accepted here?'  quest in the Netherlands (may be also in other EU countries)  seems to be an appropriate choice.

**Comment by mnalis** [comment]
I think that the reason for disabling that quest in most countries is [QUEST GUIDELINES](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md), in particular:

- :zzz: No spam: It must be possible to determine whether the quest should reasonably be asked. A quest which is to be answered in 99% of the time with the same answer is not a good quest, don't bore the users. I.e. asking for any road if it is a one-way road, is silly, because the vast majority of all roads will not be one-ways.

It is a matter of understanding that mapper time is valuable, and it should not be wasted needlessly. Also, spamming the OSM database with implied keys is bad for database (it needlessly grows and becomes slow, require more space on mobile devices etc).

However, what should be found with **certainty** is if it is **legal** for shops in Netherlands to refuse cash. If it is legal, and it is indeed closer to 5% no-cash stores, then it might be enabled. If it is however **illegal**, I do not think that it should not be enabled -- encouraging users to map illegal activities is not a good idea.

- See also related upstream issues https://github.com/streetcomplete/StreetComplete/issues/4286 and https://github.com/streetcomplete/StreetComplete/issues/1573

**Comment by meiphoo7-Mae** [comment]
I looked it up on the website of the Dutch government and I found this: https://www.rijksoverheid.nl/onderwerpen/geldzaken/vraag-en-antwoord/kan-ik-met-een-wettig-betaalmiddel-overal-betalen

It says:

----
**Can I pay everywhere with legal tender?**
The law does not require anyone to accept legal tender. Retailers may refuse cash (bills and coins) or payment by debit or credit card. However, retailers usually indicate which payment methods they do not accept. For example through window stickers or checkout stickers.

**Refuse cash**
A retailer decides for himself which means of payment he accepts.

----
The remainder of that page is about how things are implemented.

So the second newspaper article I mentioned is right about that it is not legally required.

And AFAIC the spam reason you mentioned is not valid here because a lot of quests that SCEE and/or SC has are spammy in certain ways. In the Netherlands a lot of things are not regulated by law. For example walking on a random road outside a village is not forbidden by law (unless there are signs) but I wouldn't do it in a lot of cases because cars drive 50 mph or faster.
The same goes for parking on a random road. Parking outside a village on a 50 mph road is not explicitly forbidden by law but I assume that if you do so you'll still get fined by the police because of causing danger.

I feel that users who are not able or responsible enough to use advanced software with common sense should refrain to do so and it is not the responsibility of the developer to limit software because of potential abuse.
I use SCEE because of the features it has that SC hasn't and of course if I'm determined enough I can still add alleged spammy information to OSM anyway by using editors like Vespucci, JOSM or even the editors on the OSM website itself.

**Comment by Misalf-git** [comment]
> If it is however illegal, I do not think that it should not be enabled --

I'm slightly confused about the double-not, but the statement seems to be going towards approving the proposal. So, all good.

However, this

> and it is not the responsibility of the developer to limit software because of potential abuse.

With mindlessly creating tools of mass destruction comes great responsibility.

> I feel that users who are not able or responsible enough to use advanced software with common sense should refrain to do so

There shall be light!

**Comment by Helium314** [comment]
> according to research done by an organisation for senior/elderly citizens about 2-5% of the shops only accepts electronic payments

This (_with a link_) and https://www.rijksoverheid.nl/onderwerpen/geldzaken/vraag-en-antwoord/kan-ik-met-een-wettig-betaalmiddel-overal-betalen might even be enough to enable quest in NL in StreetComplete.
NL and UK have the same number of shops with `payment:cash=no`, and the quest is enabled for UK.

So maybe you could open an issue in SC repo, and I'll enable the quest for SCEE if it gets rejected there.

> It is a matter of understanding that mapper time is valuable, and it should not be wasted needlessly. Also, spamming the OSM database with implied keys is bad

The guidelines are much relaxed in SCEE, but indeed the unwanted / needless tag spam is the only one I want to have enforced.
Though I have the impression that enabling the quest in NL would be acceptable (see above).

> With mindlessly creating tools of mass destruction comes great responsibility.

Well, you can do the same mass destruction with any other editor, so we'll be fine _in this case_.

**Comment by matkoniecz** [comment]
> I think that the reason for disabling that quest in most countries is [QUEST GUIDELINES](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md), in particular:
>
>    zzz No spam

Yes, exactly.

**Comment by matkoniecz** [comment]
I enabled it for Netherlands in SC, as opt-in quest.

**Comment by Helium314** [comment]
Ok, then I'll close this.
