### ISSUE TITLE
Extend the "Add service building type" quest

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#456]
Referred from #453 this is a collection of steps to enhance the "Add service building type" quest.

**Current keys & values**

| Quest Answer  | Tags | 
| ------------- | ------------- |
| substation   | power=substation + substation=minor_distribution  |
| gas  | pipeline=substation + substation=distribution + substance=gas |
| water_well | man_made=water_well |
| reservoir_covered | man_made=reservoir_covered  |
| pumping_station  | man_made=pumping_station  |

**Possible new tags**

* Other `power=*` values, but 98.08 % of all `power=*` on `building=service` are `power=substation`
* `service=utility` - no wiki page / no explanation found. currently 23.545 uses on `building=service` (5.67 %)
* `utility=gas|water` - more or less 300 in europe
* `utility=power` - currently 6.950 uses on `building=service` (1.69 %)
* `utility=telecom` - currently 2.030 uses on `building=service` (0.49 %)
* `utility=communication` - for buildings near communication towers?
* `man_made=monitoring_station`
* `man_made=wastewater_plant`
* `telecom=internet_exchange` or `exchange` (only when technican can stand inside)

**See also**
* https://wiki.openstreetmap.org/wiki/Key:utility
* https://wiki.openstreetmap.org/wiki/Tag:building%3Dservice

@Helium314 Please feel free to add your thoughts here.

**Comment by rskedgell** [comment]
Ventilation shafts might have been a candidate, but the wiki for man_made=ventilation_shaft has building=yes struck out (without explanation) and railway=ventilation_shaft has very little documentation or usage. Perhaps the combination of those with building=service could be excluded from the quest, but not suggested as answers (not yet, anyway)?

**Comment by Helium314** [comment]
I dug out my old attempt at extending the quest and updated it to a more current state: https://github.com/Helium314/SCEE/commit/59c71c791c522c62ba87a560390ee70f92aa3936

It basically works, using the UI of the building type quest. But there are no icons (which looks a little weird, but adding icons can be a lot of work) and the displayed text is just a placeholder.
Most of the necessary work is adding more items and ensuring correct tagging (that's where I stopped due to lack of interest in service building details).
Advantage of utility and UI is that it's possible to answer with a category if the exact type is unclear / unknown.

I had also added a note in there, that it should be rather simple to extend this to other things like street cabinets (just with somewhat different categories / selectable answers).

If any of you wants to make a proper list or finish the quest, you can take the commit and start a PR (on `modified` or on `service_building` branch).

**Comment by mnalis** [comment]
Yeah, that looks like it could fix my issue  where answer is named just _"Substation"_  while it means _"Power substation"_ instead. That always confuses me _("yeah, of course it is **sub**station as it is relatively small, but does it mean power substation, gas substation, water substation... ?" so I have to use process of elimination to deduce that it probably means electrical/power/transformer substation)_

**Comment by Helium314** [comment]
@mnalis instead of going through this process every time, you could just open a PR for changing the text. Though this change could as well be part of the quest update possibly happening soon™

@mcliquid if you can provide some list of service buildings like `COVERED_RESERVOIR(listOf("utility" to "water", "man_made" to "reservoir_covered"))` and proper names, the most important part is already done.
Icons would be nice, but at the same time are a lot of work. I guess the form looks ok without icons too...
As for the code, I can help with things or do that part myself if you prefer.

**Comment by mnalis** [comment]
> @mnalis instead of going through this process every time, you could just open a PR for changing the text. Though this change could as well be part of the quest update possibly happening soon™

I know and I would, but that quests happens rarely and so I always forget before I get to computer :smiley_cat:
(which is also why I forget what it means -- if the quest was happening often, I'd probably remember what it meant last time :smile: )
 
Now I remembered and was in front of computer, but didn't want to step on anyone's toes as the codebase seems to be changing; so I just dropped the comment not to forget it again :)

**Comment by Helium314** [comment]
> so I always forget before I get to computer

Oh I know that too well... sometimes I just write such things in the phone calendar for later that day, and hope then I can still remember enough to understand that cryptic short message from 4 hours ago.

**Comment by Helium314** [comment]
PR for creating extending the service building list: #464
