### ISSUE TITLE
Add `natural=tree` to `leaf_type`-quest/Enable ⚙️ for `leaf_type=` quest 

### ISSUE THREAD

**Issue by wielandb** [Helium314/SCEE#460]
**Use case**
I would like to be able to add `leaf_type=` to single trees as well, so e.g. 3D-renderers can be certain what kind of model to put in a render.

**Proposed Solution**
Either, add `natural=tree` to the element selection for the leaf_type-quest, maybe excluding trees where the tree genus quest has already been answered.

Or, if it is deemed unwanted to make every user who enabled the quest to see the quest for all trees, maybe the cog could be enabled for this quest so the element selection could be edited like many other quests allow.

**Comment by mnalis** [comment]
> Or, if it is deemed unwanted to make every user who enabled the quest to see the quest for all trees, maybe the cog could be enabled for this quest so the element selection could be edited like many other quests allow.

I think adding cog to the existing quest would be best solution.

Basic idea being that SCEE with default out-of-the-box config should be as similar to StreetComplete as possible, so users can choose to enable **only** extra stuff that they actually want (instead of being overwhelmed by full power that SCEE can unleash -- at the expense of added visual crowding and complexity, of course).

Thus, asking for leaf type for every single tree in the park (as they are often mapped!) should not happen by default, but only when user explicitly requests that (and adding cog is simplest and most universal way to do it)

**Comment by Helium314** [comment]
Added in https://github.com/Helium314/SCEE/commit/28ede3a99e52d885ffedf905b2b79c92893abd5e, but not yet tested.
There is now an option to ask for single trees without species or genus.
