### ISSUE TITLE
New Quest: What is the access at this gate/barrier?

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#474]
### General
Affected tag(s) to be modified/added: [access](https://wiki.openstreetmap.org/wiki/Key:access) or [locked](https://wiki.openstreetmap.org/wiki/Key:locked) and/or [gate:type](https://wiki.openstreetmap.org/wiki/Key:[access](gate:type))
Question asked: **What is the access at this gate/barrier?**

### Abstract

I add a lot of barriers to OpenStreetMap when I see them in the aerial photography. These can be lift_gate's, gate's or other barriers. You can't see the `access` from the aerial photo, this would have to be done on site.

Here I would like to start a small collection of ideas, how exactly the filter could look like and which values make sense when.

The goal should be that one supplements the appropriate access at barriers, which can be closed for some transport modes in some kind. This helps routing software to decide depending on the means of transport whether this may pass through here.

**Element selection:** 
```
nodes with barrier
and (
!access or !bicycle or !foot or !motor_vehicle
)
```

**Metadata needed:** 

**Proposed UI:**
A multi selection should be considered to select more than one access-value. Maybe also the recycling quest would be suitable, but with an major option for `access=all`.

What do you folks think about this?

**Comment by mnalis** [comment]
Maybe it would be simpler to just show existing `Other answers` / `Add accesss...` menu (which only exists on quests/overlays that reference ways currently) also on barrier-related node quests?

**Comment by Helium314** [comment]
I can't really help on the tagging part, but simply showing the access dialog might not be great. Most of the values will not be used for the gate / other barrier, and time-based restrictions possibly apply to all access tags (also, will they use `opening_hours` or conditional restrictions?).
Probably we should first have some idea which access tags / values need to be used.

It might be possible to allow selection of a way, so access tags are also added to that way. But that's not going to be a simple thing...

**Comment by mnalis** [comment]
> One random example: https://www.openstreetmap.org/node/10649072530

I must admit that the purpose of that one has me puzzled, but I think I can see what you are trying to demonstrate (e.g. residential road might be public from both sides, but have barrier at middle or entry/end in order to dissuade cars from using it as a shortcut for transit, while still allowing them to reach places from either side if that is their intended destination)

> Would it make sense to display a Quest icon (e.g. with a key) for all lockable barriers (gate, lift_gate, bump_gate, sliding_gate) and then display the existing access popup?

If you enabled `POI: Traffic` quest, barriers should be shown there I think (and then, if `Add access...` menu was enabled for them, you could add access restrictions -- or click `show/edit tags` in expert mode and add them manually which _works already_ if you know the raw tags by heart). 

But why only gate, lift_gate, bump_gate, sliding_gate? [Bollards](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbollard#Types) and others (cycle barriers...) could be (re)moveable too. 

E.g. I've seen it quite often that `barrier=bollard` + `bollard=foldable` + `motor_vehicle=private` + `bicycle=yes` + `foot=yes` to prevent non-resident cars from using a residential road as a transit shortcut and making noise all the time. Or `barrier=bollard` + `bollard=rising` + `motor_vehicle=customers` + `motor_vehicle:conditional = no @ (22:00-08:00)`  to prevent entrance during night etc.

And adding legal access rights have uses even if barriers are unremovable and unlockable (indeed, there might be signed access restrictions even on `barrier=entrance` which does not have any technical means to prevent passage of people/vehicles)

**Comment by mnalis** [comment]
> I've thought about this a bit more and am considering whether a `locked=yes/no` would be sufficient for the first step. 

Makes sense to me, that certainly should be much less problematic! 
I'd probably change text to _"Is this gate (usually) locked?"_ to sync it with its [wiki](https://wiki.openstreetmap.org/wiki/Key:locked) definition, though.
