### ISSUE TITLE
New Quest: How is the trail visibility on this path? (`trail_visibility`)

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#478]
### General
Affected tag(s) to be modified/added: [trail_visibility](https://wiki.openstreetmap.org/wiki/Key:trail_visibility)
Question asked: **How is the trail visibility on this path?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [ ] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
ways with (
highway = path
and !trail_visibility
and surface = UNPAVED // maybe only ground, grass, rock, sand etc.
// maybe only ways with sac_scale?
)
```

**Proposed UI:**
Duplication of smoothness quest with images of the trails from the wiki.

## References
https://github.com/streetcomplete/StreetComplete/issues/388

It's a very controversial Tag, but I would leave it to the experts to activate this quest.

**Comment by Helium314** [comment]
I would definitely limit the filter to ways with `sac_scale` and surfaces like ground, rock, dirt, grass and similar. Anything else will likely be visible. Alternatively you could exclude all the paved and some unpaved surfaces, so the quest is also shown without any `surface` tagged

**Comment by mnalis** [comment]
I'd ask only on  `sac_scale or surface ~ "ground|earth|dirt|soil|grass|sand|mud|ice|salt|snow|rock|stone"`; because:

- asking on anything not paved is bound to be asked in too many places; and the filter should be configurable anyway in SCEE so people can tweak it to their liking.
- If marked with `sac_scale`, there is probably a reason for that (e.g. mountain path etc), so adding visibility would probably be useful.

**Comment by mnalis** [comment]
Also, it would probably make sense to _exclude_ [lit=yes](http://overpass-turbo.eu/s/1CO4) from the quest

**Comment by Helium314** [comment]
> I'd ask only on `sac_scale or surface ~ "ground|earth|dirt|soil|grass|sand|mud|ice|salt|snow|rock|stone"`; because:

Do you really mean to ask for _sac_scale __or__ surface_? Then there there must be additional filters, as the quest should absolutely not be asked e,g, for [this path](https://www.openstreetmap.org/way/311798138).
With `and` instead of `or` the filter seems fine, plus it's very simple to switch to `or` for users who want more quests.

**Comment by HolgerJeromin** [comment]
> Then there there must be additional filters, as the quest should absolutely not be asked e,g, for this path.

Your path with `surface=asphalt` does not match `surface ~ "ground|earth|dirt|soil|grass|sand|mud|ice|salt|snow|rock|stone"`

**Comment by Helium314** [comment]
Surface isn't even checked due to `or` after `sac_scale`

**Comment by HolgerJeromin** [comment]
Sorry, I missed the sac_scale=hiking in your example.

**Comment by mnalis** [comment]
> Do you really mean to ask for sac_scale or surface? Then there there must be additional filters, as the quest should absolutely not be asked e,g, for [this path](https://www.openstreetmap.org/way/311798138).

Yeah, I actually did mean what I wrote, but I did _not envision_ that some people would apparently put `sac_scale=hiking` on regular urban asphalt sidewalks (why would they do that, that sidewalk is surely not marked as "T1" and it does not add useful information?! It makes even less sense that adding `mtb:scale=0` to all urban cycleways). Oh well. But since they apparently do so, then I'd modify that as:

`(sac_scale and sac_scale != hiking) or surface ~ "ground|earth|dirt|soil|grass|sand|mud|ice|salt|snow|rock|stone"`

>  With and instead of or the filter seems fine, plus it's very simple to switch to or for users who want more quests.

That is also valid alternative. It might be little on restrictive side (i.e. not produce much quests), but as you say, users of SCEE can tune it up themselves; it is just a default there. Although if that route is taken, I'd rather just ignore `sac_scale` tag at all and only look at `surface` tag.
