### ISSUE TITLE
Is this piste lit? (`piste:lit=yes/no`)

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#491]
### General
Affected tag(s) to be modified/added: [piste:lit](https://wiki.openstreetmap.org/wiki/Key:piste:lit)
Question asked: **Is this piste lit?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
ways, relations with
          piste:type ~ downhill|nordic|sled|ski_jump|ice_skate
          and !piste:lit
```

**Proposed UI:**
* simple OsmFilterQuestType quest only with Yes / No answers

**Comment by HolgerJeromin** [comment]
>  💤 Not an overwhelming percentage of quests have the same answer (No spam)

Most will get "no" in my experience.

**Comment by Helium314** [comment]
I don't really like adding a yet another lit quest, as the title of the way lit quest is already quite generic.
But use of `piste:lit` instead of `lit` means that adding a quest setting to ask for pistes would be more work than adding such a quest.

So you can implement the quest

**Comment by HolgerJeromin** [comment]
What about extending the overlay?

**Comment by HolgerJeromin** [comment]
Hmm. We would have the problem with mixed highway and piste ways. 
There we should have lit only but with only piste ways there should be piste:lit tags. 
I do not think this complex code is maintainable in this fork.

**Comment by Helium314** [comment]
The lit overlay barely changed since the start, and I don't expect larger changes that would cause issues with maintainability of additional code.
But with mixed highway/piste ways the overlay form would need to be adjusted too to show two lit icons when necessary. I'd expect this is too much work...

Users could add a custom overlay. It's a bit less convenient than a normal overlay, but not that much.
Using `piste:type` as filter and `!piste:lit` for coloring only requires manually entering `yes` and `no` once, afterwards editing should be quick.
