### ISSUE TITLE
Trail not multi-coloured on 2024-04-01

### ISSUE THREAD

**Issue by goldfndr** [Helium314/SCEE#527]
Yesterday, when I saw a cat with a Pop-Tart body instead of *the blue dot*, I was surprised to see a solid coloured trail behind it. [Tradition](https://nyancatcollection.com/) seems to obligate the cat's trail to be [multi-coloured](https://pbs.twimg.com/profile_banners/281670654/1655235527/1080x360).

**How to Reproduce**
Change date in system settings to 2024-04-01, launch SCEE, keep in foreground (moving if needed) until a trail is visible. (I did not test other years, but I did check both "Auto" theme and "Dark" theme.)

**Expected Behavior**
A multi-coloured track trails the detected location.

**Does it happen in normal StreetComplete?**
As of 57.1, normal SC exceeds expectations: not merely displaying a rainbow-themed trail, it *rotates* the spectrum of color in said trail. At least as perceived by me for a very short trail. On the other hand, if normal SC is launched on 2024-04-01 and the date is changed, the cat stays, with a solid-coloured trail.

**Versions affected**
SCEE 57.0 on Android 14 on a Samsung Galaxy Z Fold3

**Comment by Helium314** [comment]
I remember doing something there because it was inconvenient to deal with (needing additional scene files for theme combinations).
I'll close this because I don't want to invest any of my time on this, and mostly because we'll switch to MapLibre soon, where the old tangram scene files will not be used anyway.
